package com.fooddelivery.common.enums;

public enum AuditAction {
    ORGANISATION_CREATED, ORGANISATION_RENAMED, ORGANISATION_SUSPENDED, ORGANISATION_REINSTATED,
    ORGANISATION_CLOSED, MEMBER_INVITED, INVITATION_ACCEPTED, INVITATION_DECLINED, INVITATION_REVOKED,
    INVITATION_EXPIRED, MEMBER_ROLE_CHANGED, MEMBER_REMOVED, OWNERSHIP_TRANSFERRED,
    APPLICATION_SUBMITTED, APPLICATION_APPROVED, APPLICATION_REJECTED, APPLICATION_SUSPENDED,
    APPLICATION_REINSTATED, KYC_DOCUMENT_VIEWED, ADMIN_STEP_UP, TOPUP_REQUESTED, TOPUP_SETTLED,
    TOPUP_FAILED, CREATIVE_APPROVED, CREATIVE_REJECTED, CAMPAIGN_ACTIVATED, CAMPAIGN_PAUSED
}
