package com.fooddelivery.common.enums;

public enum OrderStatus {
    CREATED,
    PAID,
    AWAITING_DELAY_APPROVAL,
    ACCEPTED,
    PREPARING,
    READY_FOR_PICKUP,
    DISPATCHED,
    OUT_FOR_DELIVERY,
    DELIVERED,
    CANCELLED,
    CANCELLED_BY_RESTAURANT,
    DELIVERY_FAILED,
    PARTIALLY_REFUNDED,
    CANCELLED_AND_REFUNDED
}
