package com.fooddelivery.common.constants;

public enum EventType {
    // Order lifecycle events
    ORDER_CREATED(10),
    ORDER_PAID(20),
    ORDER_ACCEPTED(30),
    ORDER_PREPARING(40),
    ORDER_READY(50),
    ORDER_DELIVERED(60),
    ORDER_REJECTED(70),
    ORDER_AT_RESTAURANT(80),
    ORDER_STATUS_UPDATED(90),
    ORDER_STATUS_SYNC(100),

    // Cancellation events
    ORDER_CANCELLED(110),
    ORDER_CANCELLED_BY_RESTAURANT(120),
    ORDER_CANCELLED_BY_CUSTOMER(130),
    ORDER_CANCELLED_BY_ADMIN(135),

    // Delay approval events
    ORDER_DELAY_APPROVAL_REQUESTED(140),
    ORDER_DELAY_APPROVED(150),
    ORDER_DELAY_REJECTED(160),

    // Dispatch events
    DISPATCH_CANDIDATE_FOUND(170),
    DISPATCH_FAILED(180),
    DRIVER_ASSIGNED(190),
    ORDER_DRIVER_REJECTED(200),
    MANUAL_INTERVENTION_REQUIRED(205),
    FORCE_ASSIGN_DRIVER(206),

    // Delivery status values
    DELIVERY_FAILED(210),

    // Notification events
    NOTIFICATION_REQUEST(220),
    NOTIFICATION_DISPATCH(225),

    // Payment events
    PAYMENT_WEBHOOK(230),
    PAYMENT_COMPLETED(240),
    PAYMENT_FAILED(250),
    PAYMENT_REFUNDED(260),
    PAYMENT_REFUND_REQUESTED(270),
    PAYMENT_PARTIALLY_REFUNDED(275),
    ORDER_PARTIALLY_REFUNDED(276),
    
    // Ledger events
    LEDGER_TRANSACTION_REQUEST(280),
    LEDGER_TRANSACTION_FAILED(285),
    LEDGER_REVERSAL_REQUEST(288),
    LEDGER_BULK_TRANSACTION_REQUEST(289),
    
    OUTLET_ACTIVATED(290),
    MENU_UPDATED(295),
    OUTLET_DEACTIVATED(300),

    // Brand events
    BRAND_CREATED(310),

    // Advertisement events
    AD_CAMPAIGN_CREATED(320),
    AD_CAMPAIGN_UPDATED(330),
    AD_CAMPAIGN_PAUSED(340),
    AD_CAMPAIGN_RESUMED(343),
    AD_CAMPAIGN_COMPLETED(344),
    AD_CAMPAIGN_DELETED(346),
    AD_CREATIVE_PENDING(347),
    AD_CREATIVE_APPROVED(348),
    AD_CREATIVE_REJECTED(349),
    AD_CAMPAIGN_BUDGET_EXHAUSTED(350),
    AD_CAMPAIGN_PACING_UPDATED(355),
    AD_IMPRESSION_BILLED(360),
    AD_CLICK_BILLED(370),
    AD_CONVERSION_BILLED(380),
    AD_WALLET_TOPUP_REQUEST(390),
    AD_WALLET_TOPUP_COMPLETED(400),
    AD_BUDGET_ALERT(410),
    
    // Generic Wallet events
    REFUND_GENERATED(420),
    REVERSAL_GENERATED(425),
    EARNINGS_GENERATED(430),
    PAYOUT_GENERATED(440),
    
    // Chat events
    CHAT_REFUND_QUOTE_REQUESTED(450),
    CHAT_REFUND_REQUESTED(460),
    CHAT_REFUND_QUOTE_RESPONSE(470),
    CHAT_REFUND_DECISION(480),
    CHAT_REFUND_ERROR(490),
    
    // Review events
    REVIEW_CREATED(500);

    private final int code;

    EventType(int code) {
        this.code = code;
    }

    public int getCode() {
        return code;
    }
}
